version: 2.1
jobs:
  build:
    docker:
      - image: "golang:1.12.0-alpine3.9"
    steps:
      - run: apk add --update --no-cache ca-certificates git
      - checkout
      - run: go mod download
      - run: go build .
  tileserver-base-env-vars:
  #FIXME - find a way to inject env vars directly from workflow defn 
    docker:
      - image: "alpine:3.9"
    steps:
      - run: apk add --no-cache ca-certificates
      - run: mkdir -p /tmp/workspace
      - run: echo "export DOCKER_FILE=Dockerfile" >> /tmp/workspace/env-vars
      - run: echo "export SERVICE_NAME=tileserver" >> /tmp/workspace/env-vars
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - env-vars
  tileserver-tag-env-vars:
    docker:
      - image: "alpine:3.9"
    steps:
      - run: apk add --no-cache ca-certificates
      - attach_workspace:
          at: /tmp/workspace
      - run: echo "export TAG=$CIRCLE_TAG" >> /tmp/workspace/env-vars
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - env-vars
  tileserver-branch-env-vars:
    docker:
      - image: "alpine:3.9"
    steps:
      - run: apk add --no-cache ca-certificates
      - attach_workspace:
          at: /tmp/workspace
      - run: echo "export TAG=$CIRCLE_SHA1" >> /tmp/workspace/env-vars
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - env-vars
  upload:
    docker: 
      #FIXME: find image that has docker and also make sure it has circleci creds
      - image: "circleci/golang:1.8.6-jessie"
    steps: 
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/env-vars >> $BASH_ENV
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: "docker build -f $DOCKER_FILE -t $DOCKER_HUB_REPO/$SERVICE_NAME:$TAG ."
      - run: "docker push $DOCKER_HUB_REPO/$SERVICE_NAME:$TAG"
workflows:
  version: 2
  tileserver: 
    jobs: 
      - build
      - tileserver-base-env-vars:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - tileserver-branch-env-vars:
          requires:
            - tileserver-base-env-vars
      - tileserver-tag-env-vars:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
             - tileserver-base-env-vars
      - upload:
          name: "tags"
          filters: 
            branches: 
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - tileserver-tag-env-vars
      - upload:
          name: "branches"
          requires:
            - tileserver-branch-env-vars
